### ISSUE TITLE
NonEmptySlice::first_mut exists

### ISSUE THREAD

**Issue by 197g** [lzutao/rust-oom#3]
Just the title. This method shouldn't exist as it creates a new mutable reference to content it does not own.

https://docs.rs/oom/0.1.0/oom/struct.NonEmptySlice.html#method.first_mut

**Comment by tesuji** [comment]
Thank you. I wanted to removed this before publishing the crate but somehow I forgot it through experiments.
Will removed it soon.

**Comment by tesuji** [comment]
Fixed in 0ebbda8f8b5177ce5ddc498c9d154e643c49756a .
Thanks again for helping me.
