### ISSUE TITLE
Advantage over slice or Vec?

### ISSUE THREAD

**Issue by pickfire** [lzutao/rust-oom#4]
Is there any advantage this crate provides over slice or Vec other than the guarantees?

**Comment by tesuji** [comment]
Yeah, it's the guarantee in type system. Nothing more.
In fact, it is just a wrapper around inner `&[T]` or `Vec<T>`.

**Comment by pickfire** [comment]
Ah, I thought there is sort of performance benefit.

**Comment by tesuji** [comment]
Maybe, some fallible methods like `first`, `split_first` now are infallible. But it should be unnoticeable.
